name: Node.js CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: 'node:12'
    steps:
      - uses: actions/checkout@v2
      - run: bash src/.buildkite/test/run.sh
        env:
          CI: true
          SKIP_GIT: true
          GITHUB_CONTEXT: ${{ toJson(github) }}
